//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:\repos\AcmeMath\AcmeMathLanguage\AcmeMath.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class AcmeMathParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, NEWLINE=35, IDENTIFIER=36, CONSTANT=37, 
		STRING=38, INTEGER=39, FLOAT=40, SKIP_=41;
	public const int
		RULE_expression = 0, RULE_obj = 1, RULE_pair = 2, RULE_arr = 3, RULE_argList = 4, 
		RULE_functionCall = 5, RULE_literal = 6;
	public static readonly string[] ruleNames = {
		"expression", "obj", "pair", "arr", "argList", "functionCall", "literal"
	};

	private static readonly string[] _LiteralNames = {
		null, "'true'", "'false'", "'?'", "'('", "')'", "'['", "']'", "'.'", "'$'", 
		"'/'", "'-'", "'+'", "'*'", "'%'", "'^'", "'<'", "'>'", "'<='", "'>='", 
		"'=='", "'!='", "'!'", "'not'", "'and'", "'&&'", "'or'", "'||'", "'{'", 
		"','", "'}'", "':'", "'alpha'", "'beta'", "'gamma'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, "NEWLINE", 
		"IDENTIFIER", "CONSTANT", "STRING", "INTEGER", "FLOAT", "SKIP_"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "AcmeMath.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static AcmeMathParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public AcmeMathParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public AcmeMathParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class MinusContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public MinusContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMinus(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class JumpLiteralContext : ExpressionContext {
		public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public JumpLiteralContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJumpLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ComparisonContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ComparisonContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComparison(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LogicOrContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public LogicOrContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicOr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SignContext : ExpressionContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public SignContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSign(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SubscriptionContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public SubscriptionContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSubscription(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PlusContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public PlusContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlus(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class JmespathContext : ExpressionContext {
		public ITerminalNode STRING() { return GetToken(AcmeMathParser.STRING, 0); }
		public JmespathContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJmespath(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class CallContext : ExpressionContext {
		public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		public CallContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LogicAndContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public LogicAndContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicAnd(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BooleanContext : ExpressionContext {
		public BooleanContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolean(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParentesesContext : ExpressionContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ParentesesContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenteses(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BitXorContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public BitXorContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBitXor(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class JsonContext : ExpressionContext {
		public ObjContext obj() {
			return GetRuleContext<ObjContext>(0);
		}
		public ArrContext arr() {
			return GetRuleContext<ArrContext>(0);
		}
		public JsonContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJson(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class GetNodeContext : ExpressionContext {
		public ITerminalNode STRING() { return GetToken(AcmeMathParser.STRING, 0); }
		public ITerminalNode[] IDENTIFIER() { return GetTokens(AcmeMathParser.IDENTIFIER); }
		public ITerminalNode IDENTIFIER(int i) {
			return GetToken(AcmeMathParser.IDENTIFIER, i);
		}
		public GetNodeContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGetNode(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AttributeContext : ExpressionContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode IDENTIFIER() { return GetToken(AcmeMathParser.IDENTIFIER, 0); }
		public AttributeContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAttribute(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FactorContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public FactorContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFactor(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LogicNotContext : ExpressionContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public LogicNotContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicNot(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 0;
		EnterRecursionRule(_localctx, 0, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 43;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				{
				_localctx = new BooleanContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 15; Match(T__0);
				}
				break;
			case T__1:
				{
				_localctx = new BooleanContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 16; Match(T__1);
				}
				break;
			case T__27:
				{
				_localctx = new JsonContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 17; obj();
				}
				break;
			case T__5:
				{
				_localctx = new JsonContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 18; arr();
				}
				break;
			case T__2:
				{
				_localctx = new JmespathContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 19; Match(T__2);
				State = 20; Match(STRING);
				}
				break;
			case IDENTIFIER:
			case CONSTANT:
			case STRING:
			case INTEGER:
			case FLOAT:
				{
				_localctx = new JumpLiteralContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 21; literal();
				}
				break;
			case T__31:
			case T__32:
			case T__33:
				{
				_localctx = new CallContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 22; functionCall();
				}
				break;
			case T__3:
				{
				_localctx = new ParentesesContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 23; Match(T__3);
				State = 24; expression(0);
				State = 25; Match(T__4);
				}
				break;
			case T__8:
				{
				_localctx = new GetNodeContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 27; Match(T__8);
				State = 37;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case STRING:
					{
					State = 28; Match(STRING);
					}
					break;
				case IDENTIFIER:
					{
					State = 29; Match(IDENTIFIER);
					State = 34;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
					while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
						if ( _alt==1 ) {
							{
							{
							State = 30; Match(T__9);
							State = 31; Match(IDENTIFIER);
							}
							} 
						}
						State = 36;
						ErrorHandler.Sync(this);
						_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			case T__10:
			case T__11:
				{
				_localctx = new SignContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 39;
				_la = TokenStream.LA(1);
				if ( !(_la==T__10 || _la==T__11) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 40; expression(9);
				}
				break;
			case T__21:
			case T__22:
				{
				_localctx = new LogicNotContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 41;
				_la = TokenStream.LA(1);
				if ( !(_la==T__21 || _la==T__22) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 42; expression(3);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 76;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 74;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
					case 1:
						{
						_localctx = new FactorContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 45;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 46;
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__9) | (1L << T__12) | (1L << T__13))) != 0)) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 47; expression(9);
						}
						break;
					case 2:
						{
						_localctx = new PlusContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 48;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 49; Match(T__11);
						State = 50; expression(8);
						}
						break;
					case 3:
						{
						_localctx = new MinusContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 51;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 52; Match(T__10);
						State = 53; expression(7);
						}
						break;
					case 4:
						{
						_localctx = new BitXorContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 54;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 55; Match(T__14);
						State = 56; expression(6);
						}
						break;
					case 5:
						{
						_localctx = new ComparisonContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 57;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 58;
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__15) | (1L << T__16) | (1L << T__17) | (1L << T__18) | (1L << T__19) | (1L << T__20))) != 0)) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 59; expression(5);
						}
						break;
					case 6:
						{
						_localctx = new LogicAndContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 60;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 61;
						_la = TokenStream.LA(1);
						if ( !(_la==T__23 || _la==T__24) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 62; expression(3);
						}
						break;
					case 7:
						{
						_localctx = new LogicOrContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 63;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 64;
						_la = TokenStream.LA(1);
						if ( !(_la==T__25 || _la==T__26) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 65; expression(2);
						}
						break;
					case 8:
						{
						_localctx = new SubscriptionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 66;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 67; Match(T__5);
						State = 68; expression(0);
						State = 69; Match(T__6);
						}
						break;
					case 9:
						{
						_localctx = new AttributeContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 71;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 72; Match(T__7);
						State = 73; Match(IDENTIFIER);
						}
						break;
					}
					} 
				}
				State = 78;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ObjContext : ParserRuleContext {
		public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		public ObjContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_obj; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObj(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjContext obj() {
		ObjContext _localctx = new ObjContext(Context, State);
		EnterRule(_localctx, 2, RULE_obj);
		int _la;
		try {
			State = 92;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 79; Match(T__27);
				State = 80; pair();
				State = 85;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__28) {
					{
					{
					State = 81; Match(T__28);
					State = 82; pair();
					}
					}
					State = 87;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 88; Match(T__29);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 90; Match(T__27);
				State = 91; Match(T__29);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PairContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(AcmeMathParser.STRING, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public PairContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pair; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPair(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PairContext pair() {
		PairContext _localctx = new PairContext(Context, State);
		EnterRule(_localctx, 4, RULE_pair);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 94; Match(STRING);
			State = 95; Match(T__30);
			State = 96; expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ArrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arr; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrContext arr() {
		ArrContext _localctx = new ArrContext(Context, State);
		EnterRule(_localctx, 6, RULE_arr);
		int _la;
		try {
			State = 111;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 98; Match(T__5);
				State = 99; expression(0);
				State = 104;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__28) {
					{
					{
					State = 100; Match(T__28);
					State = 101; expression(0);
					}
					}
					State = 106;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 107; Match(T__6);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 109; Match(T__5);
				State = 110; Match(T__6);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgListContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ArgListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argList; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgListContext argList() {
		ArgListContext _localctx = new ArgListContext(Context, State);
		EnterRule(_localctx, 8, RULE_argList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113; expression(0);
			State = 118;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__28) {
				{
				{
				State = 114; Match(T__28);
				State = 115; expression(0);
				}
				}
				State = 120;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionCallContext : ParserRuleContext {
		public FunctionCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionCall; } }
	 
		public FunctionCallContext() { }
		public virtual void CopyFrom(FunctionCallContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class AlphaContext : FunctionCallContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public AlphaContext(FunctionCallContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAlpha(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BetaContext : FunctionCallContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public BetaContext(FunctionCallContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBeta(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class GammaContext : FunctionCallContext {
		public GammaContext(FunctionCallContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGamma(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionCallContext functionCall() {
		FunctionCallContext _localctx = new FunctionCallContext(Context, State);
		EnterRule(_localctx, 10, RULE_functionCall);
		try {
			State = 136;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__31:
				_localctx = new AlphaContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 121; Match(T__31);
				State = 122; Match(T__3);
				State = 123; expression(0);
				State = 124; Match(T__28);
				State = 125; expression(0);
				State = 126; Match(T__4);
				}
				break;
			case T__32:
				_localctx = new BetaContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 128; Match(T__32);
				State = 129; Match(T__3);
				State = 130; expression(0);
				State = 131; Match(T__4);
				}
				break;
			case T__33:
				_localctx = new GammaContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 133; Match(T__33);
				State = 134; Match(T__3);
				State = 135; Match(T__4);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(AcmeMathParser.STRING, 0); }
		public ITerminalNode INTEGER() { return GetToken(AcmeMathParser.INTEGER, 0); }
		public ITerminalNode FLOAT() { return GetToken(AcmeMathParser.FLOAT, 0); }
		public ITerminalNode IDENTIFIER() { return GetToken(AcmeMathParser.IDENTIFIER, 0); }
		public ITerminalNode CONSTANT() { return GetToken(AcmeMathParser.CONSTANT, 0); }
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IAcmeMathVisitor<TResult> typedVisitor = visitor as IAcmeMathVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 12, RULE_literal);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 138;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IDENTIFIER) | (1L << CONSTANT) | (1L << STRING) | (1L << INTEGER) | (1L << FLOAT))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 0: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 8);
		case 1: return Precpred(Context, 7);
		case 2: return Precpred(Context, 6);
		case 3: return Precpred(Context, 5);
		case 4: return Precpred(Context, 4);
		case 5: return Precpred(Context, 2);
		case 6: return Precpred(Context, 1);
		case 7: return Precpred(Context, 12);
		case 8: return Precpred(Context, 11);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '+', '\x8F', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', '#', '\n', '\x2', 
		'\f', '\x2', '\xE', '\x2', '&', '\v', '\x2', '\x5', '\x2', '(', '\n', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x5', 
		'\x2', '.', '\n', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\a', '\x2', 'M', '\n', '\x2', '\f', '\x2', '\xE', '\x2', 'P', 
		'\v', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', 
		'\x3', 'V', '\n', '\x3', '\f', '\x3', '\xE', '\x3', 'Y', '\v', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', 
		'_', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', 'i', 
		'\n', '\x5', '\f', '\x5', '\xE', '\x5', 'l', '\v', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 'r', '\n', '\x5', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 'w', '\n', '\x6', 
		'\f', '\x6', '\xE', '\x6', 'z', '\v', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x5', '\a', '\x8B', '\n', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x2', '\x3', '\x2', '\t', '\x2', '\x4', '\x6', 
		'\b', '\n', '\f', '\xE', '\x2', '\t', '\x3', '\x2', '\r', '\xE', '\x3', 
		'\x2', '\x18', '\x19', '\x4', '\x2', '\f', '\f', '\xF', '\x10', '\x3', 
		'\x2', '\x12', '\x17', '\x3', '\x2', '\x1A', '\x1B', '\x3', '\x2', '\x1C', 
		'\x1D', '\x3', '\x2', '&', '*', '\x2', '\xA3', '\x2', '-', '\x3', '\x2', 
		'\x2', '\x2', '\x4', '^', '\x3', '\x2', '\x2', '\x2', '\x6', '`', '\x3', 
		'\x2', '\x2', '\x2', '\b', 'q', '\x3', '\x2', '\x2', '\x2', '\n', 's', 
		'\x3', '\x2', '\x2', '\x2', '\f', '\x8A', '\x3', '\x2', '\x2', '\x2', 
		'\xE', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x10', '\x11', '\b', '\x2', 
		'\x1', '\x2', '\x11', '.', '\a', '\x3', '\x2', '\x2', '\x12', '.', '\a', 
		'\x4', '\x2', '\x2', '\x13', '.', '\x5', '\x4', '\x3', '\x2', '\x14', 
		'.', '\x5', '\b', '\x5', '\x2', '\x15', '\x16', '\a', '\x5', '\x2', '\x2', 
		'\x16', '.', '\a', '(', '\x2', '\x2', '\x17', '.', '\x5', '\xE', '\b', 
		'\x2', '\x18', '.', '\x5', '\f', '\a', '\x2', '\x19', '\x1A', '\a', '\x6', 
		'\x2', '\x2', '\x1A', '\x1B', '\x5', '\x2', '\x2', '\x2', '\x1B', '\x1C', 
		'\a', '\a', '\x2', '\x2', '\x1C', '.', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\'', '\a', '\v', '\x2', '\x2', '\x1E', '(', '\a', '(', '\x2', '\x2', 
		'\x1F', '$', '\a', '&', '\x2', '\x2', ' ', '!', '\a', '\f', '\x2', '\x2', 
		'!', '#', '\a', '&', '\x2', '\x2', '\"', ' ', '\x3', '\x2', '\x2', '\x2', 
		'#', '&', '\x3', '\x2', '\x2', '\x2', '$', '\"', '\x3', '\x2', '\x2', 
		'\x2', '$', '%', '\x3', '\x2', '\x2', '\x2', '%', '(', '\x3', '\x2', '\x2', 
		'\x2', '&', '$', '\x3', '\x2', '\x2', '\x2', '\'', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', '\'', '\x1F', '\x3', '\x2', '\x2', '\x2', '(', '.', '\x3', 
		'\x2', '\x2', '\x2', ')', '*', '\t', '\x2', '\x2', '\x2', '*', '.', '\x5', 
		'\x2', '\x2', '\v', '+', ',', '\t', '\x3', '\x2', '\x2', ',', '.', '\x5', 
		'\x2', '\x2', '\x5', '-', '\x10', '\x3', '\x2', '\x2', '\x2', '-', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '-', '\x13', '\x3', '\x2', '\x2', '\x2', '-', 
		'\x14', '\x3', '\x2', '\x2', '\x2', '-', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '-', '\x17', '\x3', '\x2', '\x2', '\x2', '-', '\x18', '\x3', '\x2', 
		'\x2', '\x2', '-', '\x19', '\x3', '\x2', '\x2', '\x2', '-', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '-', ')', '\x3', '\x2', '\x2', '\x2', '-', '+', '\x3', 
		'\x2', '\x2', '\x2', '.', 'N', '\x3', '\x2', '\x2', '\x2', '/', '\x30', 
		'\f', '\n', '\x2', '\x2', '\x30', '\x31', '\t', '\x4', '\x2', '\x2', '\x31', 
		'M', '\x5', '\x2', '\x2', '\v', '\x32', '\x33', '\f', '\t', '\x2', '\x2', 
		'\x33', '\x34', '\a', '\xE', '\x2', '\x2', '\x34', 'M', '\x5', '\x2', 
		'\x2', '\n', '\x35', '\x36', '\f', '\b', '\x2', '\x2', '\x36', '\x37', 
		'\a', '\r', '\x2', '\x2', '\x37', 'M', '\x5', '\x2', '\x2', '\t', '\x38', 
		'\x39', '\f', '\a', '\x2', '\x2', '\x39', ':', '\a', '\x11', '\x2', '\x2', 
		':', 'M', '\x5', '\x2', '\x2', '\b', ';', '<', '\f', '\x6', '\x2', '\x2', 
		'<', '=', '\t', '\x5', '\x2', '\x2', '=', 'M', '\x5', '\x2', '\x2', '\a', 
		'>', '?', '\f', '\x4', '\x2', '\x2', '?', '@', '\t', '\x6', '\x2', '\x2', 
		'@', 'M', '\x5', '\x2', '\x2', '\x5', '\x41', '\x42', '\f', '\x3', '\x2', 
		'\x2', '\x42', '\x43', '\t', '\a', '\x2', '\x2', '\x43', 'M', '\x5', '\x2', 
		'\x2', '\x4', '\x44', '\x45', '\f', '\xE', '\x2', '\x2', '\x45', '\x46', 
		'\a', '\b', '\x2', '\x2', '\x46', 'G', '\x5', '\x2', '\x2', '\x2', 'G', 
		'H', '\a', '\t', '\x2', '\x2', 'H', 'M', '\x3', '\x2', '\x2', '\x2', 'I', 
		'J', '\f', '\r', '\x2', '\x2', 'J', 'K', '\a', '\n', '\x2', '\x2', 'K', 
		'M', '\a', '&', '\x2', '\x2', 'L', '/', '\x3', '\x2', '\x2', '\x2', 'L', 
		'\x32', '\x3', '\x2', '\x2', '\x2', 'L', '\x35', '\x3', '\x2', '\x2', 
		'\x2', 'L', '\x38', '\x3', '\x2', '\x2', '\x2', 'L', ';', '\x3', '\x2', 
		'\x2', '\x2', 'L', '>', '\x3', '\x2', '\x2', '\x2', 'L', '\x41', '\x3', 
		'\x2', '\x2', '\x2', 'L', '\x44', '\x3', '\x2', '\x2', '\x2', 'L', 'I', 
		'\x3', '\x2', '\x2', '\x2', 'M', 'P', '\x3', '\x2', '\x2', '\x2', 'N', 
		'L', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\x3', '\x2', '\x2', '\x2', 
		'O', '\x3', '\x3', '\x2', '\x2', '\x2', 'P', 'N', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'R', '\a', '\x1E', '\x2', '\x2', 'R', 'W', '\x5', '\x6', '\x4', 
		'\x2', 'S', 'T', '\a', '\x1F', '\x2', '\x2', 'T', 'V', '\x5', '\x6', '\x4', 
		'\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'V', 'Y', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'U', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'Z', '\x3', '\x2', '\x2', '\x2', 'Y', 'W', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '[', '\a', ' ', '\x2', '\x2', '[', '_', '\x3', '\x2', '\x2', 
		'\x2', '\\', ']', '\a', '\x1E', '\x2', '\x2', ']', '_', '\a', ' ', '\x2', 
		'\x2', '^', 'Q', '\x3', '\x2', '\x2', '\x2', '^', '\\', '\x3', '\x2', 
		'\x2', '\x2', '_', '\x5', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\a', 
		'(', '\x2', '\x2', '\x61', '\x62', '\a', '!', '\x2', '\x2', '\x62', '\x63', 
		'\x5', '\x2', '\x2', '\x2', '\x63', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x64', '\x65', '\a', '\b', '\x2', '\x2', '\x65', 'j', '\x5', '\x2', '\x2', 
		'\x2', '\x66', 'g', '\a', '\x1F', '\x2', '\x2', 'g', 'i', '\x5', '\x2', 
		'\x2', '\x2', 'h', '\x66', '\x3', '\x2', '\x2', '\x2', 'i', 'l', '\x3', 
		'\x2', '\x2', '\x2', 'j', 'h', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\x3', 
		'\x2', '\x2', '\x2', 'k', 'm', '\x3', '\x2', '\x2', '\x2', 'l', 'j', '\x3', 
		'\x2', '\x2', '\x2', 'm', 'n', '\a', '\t', '\x2', '\x2', 'n', 'r', '\x3', 
		'\x2', '\x2', '\x2', 'o', 'p', '\a', '\b', '\x2', '\x2', 'p', 'r', '\a', 
		'\t', '\x2', '\x2', 'q', '\x64', '\x3', '\x2', '\x2', '\x2', 'q', 'o', 
		'\x3', '\x2', '\x2', '\x2', 'r', '\t', '\x3', '\x2', '\x2', '\x2', 's', 
		'x', '\x5', '\x2', '\x2', '\x2', 't', 'u', '\a', '\x1F', '\x2', '\x2', 
		'u', 'w', '\x5', '\x2', '\x2', '\x2', 'v', 't', '\x3', '\x2', '\x2', '\x2', 
		'w', 'z', '\x3', '\x2', '\x2', '\x2', 'x', 'v', '\x3', '\x2', '\x2', '\x2', 
		'x', 'y', '\x3', '\x2', '\x2', '\x2', 'y', '\v', '\x3', '\x2', '\x2', 
		'\x2', 'z', 'x', '\x3', '\x2', '\x2', '\x2', '{', '|', '\a', '\"', '\x2', 
		'\x2', '|', '}', '\a', '\x6', '\x2', '\x2', '}', '~', '\x5', '\x2', '\x2', 
		'\x2', '~', '\x7F', '\a', '\x1F', '\x2', '\x2', '\x7F', '\x80', '\x5', 
		'\x2', '\x2', '\x2', '\x80', '\x81', '\a', '\a', '\x2', '\x2', '\x81', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\a', '#', '\x2', 
		'\x2', '\x83', '\x84', '\a', '\x6', '\x2', '\x2', '\x84', '\x85', '\x5', 
		'\x2', '\x2', '\x2', '\x85', '\x86', '\a', '\a', '\x2', '\x2', '\x86', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\a', '$', '\x2', 
		'\x2', '\x88', '\x89', '\a', '\x6', '\x2', '\x2', '\x89', '\x8B', '\a', 
		'\a', '\x2', '\x2', '\x8A', '{', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x82', 
		'\x3', '\x2', '\x2', '\x2', '\x8A', '\x87', '\x3', '\x2', '\x2', '\x2', 
		'\x8B', '\r', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\t', '\b', 
		'\x2', '\x2', '\x8D', '\xF', '\x3', '\x2', '\x2', '\x2', '\r', '$', '\'', 
		'-', 'L', 'N', 'W', '^', 'j', 'q', 'x', '\x8A',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
