//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\repos\AcmeMath\IEC61131_3Lang\STParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="STParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ISTParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.translationUnitDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTranslationUnitDecl([NotNull] STParser.TranslationUnitDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] STParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.constantExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantExpr([NotNull] STParser.ConstantExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.xorExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXorExpr([NotNull] STParser.XorExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] STParser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.compareExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompareExpr([NotNull] STParser.CompareExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.equExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquExpr([NotNull] STParser.EquExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.addExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddExpr([NotNull] STParser.AddExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] STParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.powerExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPowerExpr([NotNull] STParser.PowerExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] STParser.UnaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpr([NotNull] STParser.PrimaryExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.variableAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableAccess([NotNull] STParser.VariableAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.multibitPartAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultibitPartAccess([NotNull] STParser.MultibitPartAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCall([NotNull] STParser.FuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.stmtList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtList([NotNull] STParser.StmtListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] STParser.StmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.assignStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignStmt([NotNull] STParser.AssignStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.assignmentAttempt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentAttempt([NotNull] STParser.AssignmentAttemptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.invocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvocation([NotNull] STParser.InvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.subprogCtrlStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogCtrlStmt([NotNull] STParser.SubprogCtrlStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.paramAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamAssign([NotNull] STParser.ParamAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.selectionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectionStmt([NotNull] STParser.SelectionStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] STParser.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.caseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseStmt([NotNull] STParser.CaseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.caseSelection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseSelection([NotNull] STParser.CaseSelectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.caseList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseList([NotNull] STParser.CaseListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.caseListElem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseListElem([NotNull] STParser.CaseListElemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.iterationStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterationStmt([NotNull] STParser.IterationStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.forStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStmt([NotNull] STParser.ForStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.controlVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitControlVariable([NotNull] STParser.ControlVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.forList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForList([NotNull] STParser.ForListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.whileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStmt([NotNull] STParser.WhileStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.repeatStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeatStmt([NotNull] STParser.RepeatStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.configName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfigName([NotNull] STParser.ConfigNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.resourceTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResourceTypeName([NotNull] STParser.ResourceTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.configDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfigDecl([NotNull] STParser.ConfigDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.resourceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResourceDecl([NotNull] STParser.ResourceDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.singleResourceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleResourceDecl([NotNull] STParser.SingleResourceDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.resourceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResourceName([NotNull] STParser.ResourceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.accessDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessDecls([NotNull] STParser.AccessDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.accessDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessDecl([NotNull] STParser.AccessDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.accessPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessPath([NotNull] STParser.AccessPathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.globalVarAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalVarAccess([NotNull] STParser.GlobalVarAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.accessName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessName([NotNull] STParser.AccessNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.progOutputAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgOutputAccess([NotNull] STParser.ProgOutputAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.progName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgName([NotNull] STParser.ProgNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.accessDirection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessDirection([NotNull] STParser.AccessDirectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.taskConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaskConfig([NotNull] STParser.TaskConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.taskName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaskName([NotNull] STParser.TaskNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.taskInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTaskInit([NotNull] STParser.TaskInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dataSource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataSource([NotNull] STParser.DataSourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.progConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgConfig([NotNull] STParser.ProgConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.progConfElems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgConfElems([NotNull] STParser.ProgConfElemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.progConfElem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgConfElem([NotNull] STParser.ProgConfElemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBTask"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBTask([NotNull] STParser.FBTaskContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.progCnxn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgCnxn([NotNull] STParser.ProgCnxnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.progDataSource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgDataSource([NotNull] STParser.ProgDataSourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dataSink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataSink([NotNull] STParser.DataSinkContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.configInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfigInit([NotNull] STParser.ConfigInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.configInstInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfigInstInit([NotNull] STParser.ConfigInstInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.namespaceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceDecl([NotNull] STParser.NamespaceDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.namespaceElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceElements([NotNull] STParser.NamespaceElementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.namespaceHName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceHName([NotNull] STParser.NamespaceHNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.namespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceName([NotNull] STParser.NamespaceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.usingDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingDirective([NotNull] STParser.UsingDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.pouDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPouDecl([NotNull] STParser.PouDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDecl([NotNull] STParser.ClassDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.classTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassTypeName([NotNull] STParser.ClassTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.classTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassTypeAccess([NotNull] STParser.ClassTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassName([NotNull] STParser.ClassNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.classInstanceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassInstanceName([NotNull] STParser.ClassInstanceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.interfaceDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDecl([NotNull] STParser.InterfaceDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.methodPrototype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodPrototype([NotNull] STParser.MethodPrototypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.interfaceSpecInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceSpecInit([NotNull] STParser.InterfaceSpecInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.interfaceValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceValue([NotNull] STParser.InterfaceValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.interfaceNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceNameList([NotNull] STParser.InterfaceNameListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.interfaceTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceTypeName([NotNull] STParser.InterfaceTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.interfaceTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceTypeAccess([NotNull] STParser.InterfaceTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.interfaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceName([NotNull] STParser.InterfaceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.accessSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessSpec([NotNull] STParser.AccessSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.progDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgDecl([NotNull] STParser.ProgDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.progTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgTypeName([NotNull] STParser.ProgTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.progTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgTypeAccess([NotNull] STParser.ProgTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.progAccessDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgAccessDecls([NotNull] STParser.ProgAccessDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.progAccessDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgAccessDecl([NotNull] STParser.ProgAccessDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBTypeName([NotNull] STParser.FBTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBTypeAccess([NotNull] STParser.FBTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.derivedFBName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerivedFBName([NotNull] STParser.DerivedFBNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBDecl([NotNull] STParser.FBDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBIOVarDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBIOVarDecls([NotNull] STParser.FBIOVarDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBInputDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBInputDecls([NotNull] STParser.FBInputDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBInputDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBInputDecl([NotNull] STParser.FBInputDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBOutputDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBOutputDecls([NotNull] STParser.FBOutputDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBOutputDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBOutputDecl([NotNull] STParser.FBOutputDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.otherVarDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherVarDecls([NotNull] STParser.OtherVarDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.nonRetainVarDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonRetainVarDecls([NotNull] STParser.NonRetainVarDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBBody([NotNull] STParser.FBBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.methodDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDecl([NotNull] STParser.MethodDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.methodName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodName([NotNull] STParser.MethodNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.funcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncName([NotNull] STParser.FuncNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.stdFunctionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStdFunctionName([NotNull] STParser.StdFunctionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.funcAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncAccess([NotNull] STParser.FuncAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.derivedFuncName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerivedFuncName([NotNull] STParser.DerivedFuncNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDecl([NotNull] STParser.FuncDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.ioVarDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIoVarDecls([NotNull] STParser.IoVarDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.funcVarDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncVarDecls([NotNull] STParser.FuncVarDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.funcBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncBody([NotNull] STParser.FuncBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] STParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.symbolicVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSymbolicVariable([NotNull] STParser.SymbolicVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.varAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarAccess([NotNull] STParser.VarAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.variableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableName([NotNull] STParser.VariableNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.multiElemVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiElemVar([NotNull] STParser.MultiElemVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.subscriptList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscriptList([NotNull] STParser.SubscriptListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscript([NotNull] STParser.SubscriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructVariable([NotNull] STParser.StructVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structElemSelect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructElemSelect([NotNull] STParser.StructElemSelectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.inputDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputDecls([NotNull] STParser.InputDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.inputDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputDecl([NotNull] STParser.InputDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.edgeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdgeDecl([NotNull] STParser.EdgeDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.varDeclInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDeclInit([NotNull] STParser.VarDeclInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.refVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefVarDecl([NotNull] STParser.RefVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.interfaceVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceVarDecl([NotNull] STParser.InterfaceVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.variableList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableList([NotNull] STParser.VariableListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.arrayVarDeclInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayVarDeclInit([NotNull] STParser.ArrayVarDeclInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.arrayConformand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayConformand([NotNull] STParser.ArrayConformandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.arrayConformDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayConformDecl([NotNull] STParser.ArrayConformDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structVarDeclInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructVarDeclInit([NotNull] STParser.StructVarDeclInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBDeclNoInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBDeclNoInit([NotNull] STParser.FBDeclNoInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBDeclInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBDeclInit([NotNull] STParser.FBDeclInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBName([NotNull] STParser.FBNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fBInstanceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFBInstanceName([NotNull] STParser.FBInstanceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.outputDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputDecls([NotNull] STParser.OutputDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.outputDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputDecl([NotNull] STParser.OutputDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.inOutDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInOutDecls([NotNull] STParser.InOutDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.inOutVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInOutVarDecl([NotNull] STParser.InOutVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDecl([NotNull] STParser.VarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.arrayVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayVarDecl([NotNull] STParser.ArrayVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructVarDecl([NotNull] STParser.StructVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.varDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDecls([NotNull] STParser.VarDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.retainVarDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRetainVarDecls([NotNull] STParser.RetainVarDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.locVarDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocVarDecls([NotNull] STParser.LocVarDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.locVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocVarDecl([NotNull] STParser.LocVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.tempVarDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTempVarDecls([NotNull] STParser.TempVarDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.externalVarDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternalVarDecls([NotNull] STParser.ExternalVarDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.externalDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternalDecl([NotNull] STParser.ExternalDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.globalVarName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalVarName([NotNull] STParser.GlobalVarNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.globalVarDecls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalVarDecls([NotNull] STParser.GlobalVarDeclsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.globalVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalVarDecl([NotNull] STParser.GlobalVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.globalVarSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalVarSpec([NotNull] STParser.GlobalVarSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.locVarSpecInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocVarSpecInit([NotNull] STParser.LocVarSpecInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.locatedAt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocatedAt([NotNull] STParser.LocatedAtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.strVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStrVarDecl([NotNull] STParser.StrVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.sByteStrVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSByteStrVarDecl([NotNull] STParser.SByteStrVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.sByteStrSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSByteStrSpec([NotNull] STParser.SByteStrSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dByteStrVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDByteStrVarDecl([NotNull] STParser.DByteStrVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dByteStrSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDByteStrSpec([NotNull] STParser.DByteStrSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.locPartlyVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocPartlyVarDecl([NotNull] STParser.LocPartlyVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.locPartlyVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocPartlyVar([NotNull] STParser.LocPartlyVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.varSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarSpec([NotNull] STParser.VarSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.stringSizeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringSizeSpec([NotNull] STParser.StringSizeSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.stdStringSizeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStdStringSizeSpec([NotNull] STParser.StdStringSizeSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.extStringSizeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtStringSizeSpec([NotNull] STParser.ExtStringSizeSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.directVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirectVariable([NotNull] STParser.DirectVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.localAtDirection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalAtDirection([NotNull] STParser.LocalAtDirectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.localAtType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalAtType([NotNull] STParser.LocalAtTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.refTypeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefTypeDecl([NotNull] STParser.RefTypeDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.refSpecInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefSpecInit([NotNull] STParser.RefSpecInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.refSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefSpec([NotNull] STParser.RefSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.refTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefTypeName([NotNull] STParser.RefTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.refTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefTypeAccess([NotNull] STParser.RefTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.refName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefName([NotNull] STParser.RefNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.refValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefValue([NotNull] STParser.RefValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.refAddr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefAddr([NotNull] STParser.RefAddrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.refAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefAssign([NotNull] STParser.RefAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.refDeref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefDeref([NotNull] STParser.RefDerefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.derivedTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerivedTypeAccess([NotNull] STParser.DerivedTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.stringTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringTypeAccess([NotNull] STParser.StringTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.singleElemTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleElemTypeAccess([NotNull] STParser.SingleElemTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.simpleTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleTypeAccess([NotNull] STParser.SimpleTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.subrangeTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubrangeTypeAccess([NotNull] STParser.SubrangeTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.enumTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumTypeAccess([NotNull] STParser.EnumTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructTypeAccess([NotNull] STParser.StructTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.arrayTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayTypeAccess([NotNull] STParser.ArrayTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.simpleTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleTypeName([NotNull] STParser.SimpleTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.subrangeTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubrangeTypeName([NotNull] STParser.SubrangeTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.enumTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumTypeName([NotNull] STParser.EnumTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructTypeName([NotNull] STParser.StructTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.arrayTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayTypeName([NotNull] STParser.ArrayTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dataTypeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataTypeDecl([NotNull] STParser.DataTypeDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.typeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDecl([NotNull] STParser.TypeDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.simpleTypeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleTypeDecl([NotNull] STParser.SimpleTypeDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.simpleSpecInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleSpecInit([NotNull] STParser.SimpleSpecInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.simpleSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleSpec([NotNull] STParser.SimpleSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.subrangeTypeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubrangeTypeDecl([NotNull] STParser.SubrangeTypeDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.subrangeSpecInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubrangeSpecInit([NotNull] STParser.SubrangeSpecInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.subrangeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubrangeSpec([NotNull] STParser.SubrangeSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.subrange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubrange([NotNull] STParser.SubrangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.enumTypeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumTypeDecl([NotNull] STParser.EnumTypeDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.namedSpecInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedSpecInit([NotNull] STParser.NamedSpecInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.enumSpecInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumSpecInit([NotNull] STParser.EnumSpecInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.enumValueSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueSpec([NotNull] STParser.EnumValueSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValue([NotNull] STParser.EnumValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.arrayTypeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayTypeDecl([NotNull] STParser.ArrayTypeDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.arraySpecInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArraySpecInit([NotNull] STParser.ArraySpecInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.arraySpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArraySpec([NotNull] STParser.ArraySpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.arrayInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayInit([NotNull] STParser.ArrayInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.arrayElemInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayElemInit([NotNull] STParser.ArrayElemInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.arrayElemInitValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayElemInitValue([NotNull] STParser.ArrayElemInitValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structTypeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructTypeDecl([NotNull] STParser.StructTypeDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructSpec([NotNull] STParser.StructSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structSpecInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructSpecInit([NotNull] STParser.StructSpecInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDecl([NotNull] STParser.StructDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structElemDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructElemDecl([NotNull] STParser.StructElemDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structElemName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructElemName([NotNull] STParser.StructElemNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructInit([NotNull] STParser.StructInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.structElemInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructElemInit([NotNull] STParser.StructElemInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.strTypeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStrTypeDecl([NotNull] STParser.StrTypeDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dataTypeAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDataTypeAccess([NotNull] STParser.DataTypeAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.elemTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElemTypeName([NotNull] STParser.ElemTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.numericTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericTypeName([NotNull] STParser.NumericTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.intTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntTypeName([NotNull] STParser.IntTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.signedIntTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignedIntTypeName([NotNull] STParser.SignedIntTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.unsignedIntTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnsignedIntTypeName([NotNull] STParser.UnsignedIntTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.realTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRealTypeName([NotNull] STParser.RealTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.stringTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringTypeName([NotNull] STParser.StringTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.timeTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeTypeName([NotNull] STParser.TimeTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dateTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateTypeName([NotNull] STParser.DateTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.todTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTodTypeName([NotNull] STParser.TodTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dtTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDtTypeName([NotNull] STParser.DtTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.bitStrTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitStrTypeName([NotNull] STParser.BitStrTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.boolTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolTypeName([NotNull] STParser.BoolTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.multibitTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultibitTypeName([NotNull] STParser.MultibitTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.testConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTestConstant([NotNull] STParser.TestConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] STParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.numericLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericLiteral([NotNull] STParser.NumericLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.intLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntLiteral([NotNull] STParser.IntLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.boolLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolLiteral([NotNull] STParser.BoolLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.realLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRealLiteral([NotNull] STParser.RealLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.bitStrLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitStrLiteral([NotNull] STParser.BitStrLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.timeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeLiteral([NotNull] STParser.TimeLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.duration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDuration([NotNull] STParser.DurationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.fixPoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFixPoint([NotNull] STParser.FixPointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.interval"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterval([NotNull] STParser.IntervalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.days"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDays([NotNull] STParser.DaysContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.hours"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHours([NotNull] STParser.HoursContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.minutes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinutes([NotNull] STParser.MinutesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.seconds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeconds([NotNull] STParser.SecondsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.milliseconds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMilliseconds([NotNull] STParser.MillisecondsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.microseconds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMicroseconds([NotNull] STParser.MicrosecondsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.nanoseconds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNanoseconds([NotNull] STParser.NanosecondsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.timeOfDay"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeOfDay([NotNull] STParser.TimeOfDayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.daytime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDaytime([NotNull] STParser.DaytimeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dayHour"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayHour([NotNull] STParser.DayHourContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dayMinute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDayMinute([NotNull] STParser.DayMinuteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.daySecond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDaySecond([NotNull] STParser.DaySecondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate([NotNull] STParser.DateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dateLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateLiteral([NotNull] STParser.DateLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.year"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYear([NotNull] STParser.YearContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.month"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonth([NotNull] STParser.MonthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.day"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDay([NotNull] STParser.DayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dateAndTime"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateAndTime([NotNull] STParser.DateAndTimeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.charLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharLiteral([NotNull] STParser.CharLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.charStr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharStr([NotNull] STParser.CharStrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.sByteCharStr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSByteCharStr([NotNull] STParser.SByteCharStrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.dByteCharStr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDByteCharStr([NotNull] STParser.DByteCharStrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSign([NotNull] STParser.SignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.unsignedInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnsignedInt([NotNull] STParser.UnsignedIntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.signedInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignedInt([NotNull] STParser.SignedIntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.binaryInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryInt([NotNull] STParser.BinaryIntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.octalInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOctalInt([NotNull] STParser.OctalIntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.hexInt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHexInt([NotNull] STParser.HexIntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] STParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.pointerSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerSpec([NotNull] STParser.PointerSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.pointerVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerVarDecl([NotNull] STParser.PointerVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.pointerSpecInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerSpecInit([NotNull] STParser.PointerSpecInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.pointerAddr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerAddr([NotNull] STParser.PointerAddrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="STParser.pointerValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerValue([NotNull] STParser.PointerValueContext context);
}
